<?php
/**
 * LineAmountTypes
 *
 * PHP version 5
 *
 * @category Class
 * @package  SidneyAllen\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SidneyAllen\XeroPHP\Models\Accounting;
use \SidneyAllen\XeroPHP\AccountingObjectSerializer;

/**
 * LineAmountTypes Class Doc Comment
 *
 * @category Class
 * @description Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types
 * @package  SidneyAllen\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LineAmountTypes
{
    /**
     * Possible values of this enum
     */
    const EXCLUSIVE = 'Exclusive';
    const INCLUSIVE = 'Inclusive';
    const NO_TAX = 'NoTax';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXCLUSIVE,
            self::INCLUSIVE,
            self::NO_TAX,
        ];
    }
}


